import { PrismaService } from '../prisma/prisma.service';
import { CreateProductDto } from './dto/create-product.dto';
import { UpdateProductDto } from './dto/update-product.dto';
import { ProductQueryDto } from './dto/product-query.dto';
import { Prisma } from '@prisma/client';
export declare class ProductsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(createProductDto: CreateProductDto, tenantId: string, userId: string): Promise<{
        barcodes: {
            id: string;
            tenantId: string;
            barcode: string;
            productId: string;
        }[];
        category: {
            id: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            description: string | null;
            deletedAt: Date | null;
            parentId: string | null;
        } | null;
        brand: {
            id: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            description: string | null;
            deletedAt: Date | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        internalReference: string | null;
        showroomCode: string | null;
        description: string;
        description_es: string | null;
        description_en: string | null;
        description_pt: string | null;
        composition: string | null;
        mainImageUrl: string | null;
        codigoArancelario: string | null;
        paisOrigen: string | null;
        unitOfMeasure: string | null;
        weight: Prisma.Decimal | null;
        volume: Prisma.Decimal | null;
        volumeCubicFeet: Prisma.Decimal | null;
        unitsPerBox: number | null;
        boxesPerPallet: number | null;
        minStock: number | null;
        price_a: Prisma.Decimal;
        price_b: Prisma.Decimal;
        price_c: Prisma.Decimal;
        price_d: Prisma.Decimal;
        price_e: Prisma.Decimal;
        lastFobCost: Prisma.Decimal;
        lastCifCost: Prisma.Decimal;
        weightedAvgCost: Prisma.Decimal;
        createdBy: string | null;
        updatedBy: string | null;
        deletedAt: Date | null;
        categoryId: string | null;
        brandId: string | null;
    }>;
    private detectDuplicates;
    findAll(query: ProductQueryDto, tenantId: string): Promise<{
        items: any[];
        meta: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    }>;
    findOne(id: string, tenantId: string): Promise<any>;
    private filterSensitiveData;
    update(id: string, updateProductDto: UpdateProductDto, tenantId: string, userId: string): Promise<{
        barcodes: {
            id: string;
            tenantId: string;
            barcode: string;
            productId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        internalReference: string | null;
        showroomCode: string | null;
        description: string;
        description_es: string | null;
        description_en: string | null;
        description_pt: string | null;
        composition: string | null;
        mainImageUrl: string | null;
        codigoArancelario: string | null;
        paisOrigen: string | null;
        unitOfMeasure: string | null;
        weight: Prisma.Decimal | null;
        volume: Prisma.Decimal | null;
        volumeCubicFeet: Prisma.Decimal | null;
        unitsPerBox: number | null;
        boxesPerPallet: number | null;
        minStock: number | null;
        price_a: Prisma.Decimal;
        price_b: Prisma.Decimal;
        price_c: Prisma.Decimal;
        price_d: Prisma.Decimal;
        price_e: Prisma.Decimal;
        lastFobCost: Prisma.Decimal;
        lastCifCost: Prisma.Decimal;
        weightedAvgCost: Prisma.Decimal;
        createdBy: string | null;
        updatedBy: string | null;
        deletedAt: Date | null;
        categoryId: string | null;
        brandId: string | null;
    }>;
    remove(id: string, tenantId: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        internalReference: string | null;
        showroomCode: string | null;
        description: string;
        description_es: string | null;
        description_en: string | null;
        description_pt: string | null;
        composition: string | null;
        mainImageUrl: string | null;
        codigoArancelario: string | null;
        paisOrigen: string | null;
        unitOfMeasure: string | null;
        weight: Prisma.Decimal | null;
        volume: Prisma.Decimal | null;
        volumeCubicFeet: Prisma.Decimal | null;
        unitsPerBox: number | null;
        boxesPerPallet: number | null;
        minStock: number | null;
        price_a: Prisma.Decimal;
        price_b: Prisma.Decimal;
        price_c: Prisma.Decimal;
        price_d: Prisma.Decimal;
        price_e: Prisma.Decimal;
        lastFobCost: Prisma.Decimal;
        lastCifCost: Prisma.Decimal;
        weightedAvgCost: Prisma.Decimal;
        createdBy: string | null;
        updatedBy: string | null;
        deletedAt: Date | null;
        categoryId: string | null;
        brandId: string | null;
    }>;
    bulkUpdatePrices(updates: Array<{
        productId: string;
        price_a?: number;
        price_b?: number;
        price_c?: number;
        price_d?: number;
        price_e?: number;
    }>, tenantId: string, userId: string): Promise<{
        updated: number;
        errors: string[];
    }>;
    updateImage(id: string, imageUrl: string, tenantId: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        internalReference: string | null;
        showroomCode: string | null;
        description: string;
        description_es: string | null;
        description_en: string | null;
        description_pt: string | null;
        composition: string | null;
        mainImageUrl: string | null;
        codigoArancelario: string | null;
        paisOrigen: string | null;
        unitOfMeasure: string | null;
        weight: Prisma.Decimal | null;
        volume: Prisma.Decimal | null;
        volumeCubicFeet: Prisma.Decimal | null;
        unitsPerBox: number | null;
        boxesPerPallet: number | null;
        minStock: number | null;
        price_a: Prisma.Decimal;
        price_b: Prisma.Decimal;
        price_c: Prisma.Decimal;
        price_d: Prisma.Decimal;
        price_e: Prisma.Decimal;
        lastFobCost: Prisma.Decimal;
        lastCifCost: Prisma.Decimal;
        weightedAvgCost: Prisma.Decimal;
        createdBy: string | null;
        updatedBy: string | null;
        deletedAt: Date | null;
        categoryId: string | null;
        brandId: string | null;
    }>;
    bulkImport(buffer: Buffer, tenantId: string, userId: string): Promise<{
        created: number;
        updated: number;
        errors: {
            row: number;
            error: string;
        }[];
    }>;
}
