import { CustomersService } from './customers.service';
import type { CreateCustomerDto, UpdateCustomerDto, BlockCustomerDto, ApproveCustomerDto, CreateCustomerTransactionDto, VoidTransactionDto, CreateCustomerAreaDto, UpdateCustomerAreaDto, CreateCustomerSubAreaDto, UpdateCustomerSubAreaDto, CreateSalespersonDto, UpdateSalespersonDto } from './dto';
export declare class CustomersController {
    private readonly customersService;
    constructor(customersService: CustomersService);
    createCustomer(dto: CreateCustomerDto): Promise<{
        sales: {
            id: string;
            status: import("@prisma/client").$Enums.SaleStatus;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            createdBy: string;
            branchId: string;
            notes: string | null;
            customerId: string | null;
            customerName: string | null;
            salespersonId: string | null;
            quoteNumber: string | null;
            orderNumber: string | null;
            validUntil: Date | null;
            dueDate: Date | null;
            subtotal: import("@prisma/client-runtime-utils").Decimal;
            tax: import("@prisma/client-runtime-utils").Decimal;
            discount: import("@prisma/client-runtime-utils").Decimal;
            total: import("@prisma/client-runtime-utils").Decimal;
            paymentMethod: string;
            refundAmount: import("@prisma/client-runtime-utils").Decimal;
            authorizedBy: string | null;
            authorizedAt: Date | null;
        }[];
        transactions: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            description: string;
            createdBy: string;
            branchId: string | null;
            notes: string | null;
            customerId: string;
            dueDate: Date | null;
            amount: import("@prisma/client-runtime-utils").Decimal;
            type: import("@prisma/client").$Enums.CustomerTransactionType;
            referenceId: string | null;
            referenceType: string | null;
            transactionDate: Date;
            transactionNumber: string;
            balance: import("@prisma/client-runtime-utils").Decimal;
            isVoided: boolean;
            voidedBy: string | null;
            voidedAt: Date | null;
            voidReason: string | null;
        }[];
    } & {
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        email: string | null;
        createdBy: string;
        deletedAt: Date | null;
        taxId: string | null;
        phone: string | null;
        address: string | null;
        customerType: import("@prisma/client").$Enums.CustomerType;
        priceLevel: import("@prisma/client").$Enums.PriceLevel;
        creditLimit: import("@prisma/client-runtime-utils").Decimal;
        paymentTermDays: number;
        currentBalance: import("@prisma/client-runtime-utils").Decimal;
        creditStatus: import("@prisma/client").$Enums.CreditStatus;
        isApproved: boolean;
        isBlocked: boolean;
        blockedReason: string | null;
        approvedBy: string | null;
        approvedAt: Date | null;
        notes: string | null;
    }>;
    listCustomers(search?: string, customerType?: 'CASH' | 'CREDIT', creditStatus?: string, isBlocked?: string, page?: string, limit?: string): Promise<{
        items: ({
            _count: {
                sales: number;
                transactions: number;
            };
        } & {
            id: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            email: string | null;
            createdBy: string;
            deletedAt: Date | null;
            taxId: string | null;
            phone: string | null;
            address: string | null;
            customerType: import("@prisma/client").$Enums.CustomerType;
            priceLevel: import("@prisma/client").$Enums.PriceLevel;
            creditLimit: import("@prisma/client-runtime-utils").Decimal;
            paymentTermDays: number;
            currentBalance: import("@prisma/client-runtime-utils").Decimal;
            creditStatus: import("@prisma/client").$Enums.CreditStatus;
            isApproved: boolean;
            isBlocked: boolean;
            blockedReason: string | null;
            approvedBy: string | null;
            approvedAt: Date | null;
            notes: string | null;
        })[];
        total: number;
        page: number;
        limit: number;
        totalPages: number;
    }>;
    getCustomer(id: string): Promise<{
        sales: ({
            items: ({
                product: {
                    id: string;
                    createdAt: Date;
                    updatedAt: Date;
                    tenantId: string;
                    internalReference: string | null;
                    showroomCode: string | null;
                    description: string;
                    description_es: string | null;
                    description_en: string | null;
                    description_pt: string | null;
                    composition: string | null;
                    mainImageUrl: string | null;
                    codigoArancelario: string | null;
                    paisOrigen: string | null;
                    unitOfMeasure: string | null;
                    weight: import("@prisma/client-runtime-utils").Decimal | null;
                    volume: import("@prisma/client-runtime-utils").Decimal | null;
                    volumeCubicFeet: import("@prisma/client-runtime-utils").Decimal | null;
                    unitsPerBox: number | null;
                    boxesPerPallet: number | null;
                    minStock: number | null;
                    price_a: import("@prisma/client-runtime-utils").Decimal;
                    price_b: import("@prisma/client-runtime-utils").Decimal;
                    price_c: import("@prisma/client-runtime-utils").Decimal;
                    price_d: import("@prisma/client-runtime-utils").Decimal;
                    price_e: import("@prisma/client-runtime-utils").Decimal;
                    lastFobCost: import("@prisma/client-runtime-utils").Decimal;
                    lastCifCost: import("@prisma/client-runtime-utils").Decimal;
                    weightedAvgCost: import("@prisma/client-runtime-utils").Decimal;
                    createdBy: string | null;
                    updatedBy: string | null;
                    deletedAt: Date | null;
                    categoryId: string | null;
                    brandId: string | null;
                };
            } & {
                id: string;
                tenantId: string;
                productId: string;
                quantity: import("@prisma/client-runtime-utils").Decimal;
                total: import("@prisma/client-runtime-utils").Decimal;
                unitPrice: import("@prisma/client-runtime-utils").Decimal;
                discountAmount: import("@prisma/client-runtime-utils").Decimal;
                taxAmount: import("@prisma/client-runtime-utils").Decimal;
                quantityPacked: import("@prisma/client-runtime-utils").Decimal;
                saleId: string;
            })[];
        } & {
            id: string;
            status: import("@prisma/client").$Enums.SaleStatus;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            createdBy: string;
            branchId: string;
            notes: string | null;
            customerId: string | null;
            customerName: string | null;
            salespersonId: string | null;
            quoteNumber: string | null;
            orderNumber: string | null;
            validUntil: Date | null;
            dueDate: Date | null;
            subtotal: import("@prisma/client-runtime-utils").Decimal;
            tax: import("@prisma/client-runtime-utils").Decimal;
            discount: import("@prisma/client-runtime-utils").Decimal;
            total: import("@prisma/client-runtime-utils").Decimal;
            paymentMethod: string;
            refundAmount: import("@prisma/client-runtime-utils").Decimal;
            authorizedBy: string | null;
            authorizedAt: Date | null;
        })[];
        creditAlerts: {
            id: string;
            createdAt: Date;
            tenantId: string;
            customerId: string;
            message: string;
            isResolved: boolean;
            alertType: string;
            severity: string;
            daysOverdue: number | null;
            amountOverdue: import("@prisma/client-runtime-utils").Decimal | null;
            resolvedBy: string | null;
            resolvedAt: Date | null;
        }[];
        payments: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            createdBy: string;
            notes: string | null;
            customerId: string;
            paymentMethod: import("@prisma/client").$Enums.PaymentMethod;
            amount: import("@prisma/client-runtime-utils").Decimal;
            saleId: string | null;
            paymentDate: Date;
            reference: string | null;
        }[];
        transactions: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            description: string;
            createdBy: string;
            branchId: string | null;
            notes: string | null;
            customerId: string;
            dueDate: Date | null;
            amount: import("@prisma/client-runtime-utils").Decimal;
            type: import("@prisma/client").$Enums.CustomerTransactionType;
            referenceId: string | null;
            referenceType: string | null;
            transactionDate: Date;
            transactionNumber: string;
            balance: import("@prisma/client-runtime-utils").Decimal;
            isVoided: boolean;
            voidedBy: string | null;
            voidedAt: Date | null;
            voidReason: string | null;
        }[];
    } & {
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        email: string | null;
        createdBy: string;
        deletedAt: Date | null;
        taxId: string | null;
        phone: string | null;
        address: string | null;
        customerType: import("@prisma/client").$Enums.CustomerType;
        priceLevel: import("@prisma/client").$Enums.PriceLevel;
        creditLimit: import("@prisma/client-runtime-utils").Decimal;
        paymentTermDays: number;
        currentBalance: import("@prisma/client-runtime-utils").Decimal;
        creditStatus: import("@prisma/client").$Enums.CreditStatus;
        isApproved: boolean;
        isBlocked: boolean;
        blockedReason: string | null;
        approvedBy: string | null;
        approvedAt: Date | null;
        notes: string | null;
    }>;
    updateCustomer(id: string, dto: UpdateCustomerDto): Promise<{
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        email: string | null;
        createdBy: string;
        deletedAt: Date | null;
        taxId: string | null;
        phone: string | null;
        address: string | null;
        customerType: import("@prisma/client").$Enums.CustomerType;
        priceLevel: import("@prisma/client").$Enums.PriceLevel;
        creditLimit: import("@prisma/client-runtime-utils").Decimal;
        paymentTermDays: number;
        currentBalance: import("@prisma/client-runtime-utils").Decimal;
        creditStatus: import("@prisma/client").$Enums.CreditStatus;
        isApproved: boolean;
        isBlocked: boolean;
        blockedReason: string | null;
        approvedBy: string | null;
        approvedAt: Date | null;
        notes: string | null;
    }>;
    deleteCustomer(id: string): Promise<{
        success: boolean;
    }>;
    blockCustomer(id: string, dto: BlockCustomerDto): Promise<{
        success: boolean;
    }>;
    unblockCustomer(id: string): Promise<{
        success: boolean;
    }>;
    approveCustomer(id: string, dto: ApproveCustomerDto): Promise<{
        success: boolean;
    }>;
    getAccountStatement(id: string, startDate?: string, endDate?: string): Promise<{
        customer: {
            id: string;
            name: string;
            taxId: string | null;
            currentBalance: import("@prisma/client-runtime-utils").Decimal;
            creditLimit: import("@prisma/client-runtime-utils").Decimal;
            paymentTermDays: number;
        };
        transactions: ({
            branch: {
                name: string;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            description: string;
            createdBy: string;
            branchId: string | null;
            notes: string | null;
            customerId: string;
            dueDate: Date | null;
            amount: import("@prisma/client-runtime-utils").Decimal;
            type: import("@prisma/client").$Enums.CustomerTransactionType;
            referenceId: string | null;
            referenceType: string | null;
            transactionDate: Date;
            transactionNumber: string;
            balance: import("@prisma/client-runtime-utils").Decimal;
            isVoided: boolean;
            voidedBy: string | null;
            voidedAt: Date | null;
            voidReason: string | null;
        })[];
        summary: {
            totalInvoices: number;
            totalPayments: number;
            totalInvoiced: import("@prisma/client-runtime-utils").Decimal;
            totalPaid: import("@prisma/client-runtime-utils").Decimal;
            currentBalance: import("@prisma/client-runtime-utils").Decimal;
        };
    }>;
    createTransaction(dto: CreateCustomerTransactionDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        description: string;
        createdBy: string;
        branchId: string | null;
        notes: string | null;
        customerId: string;
        dueDate: Date | null;
        amount: import("@prisma/client-runtime-utils").Decimal;
        type: import("@prisma/client").$Enums.CustomerTransactionType;
        referenceId: string | null;
        referenceType: string | null;
        transactionDate: Date;
        transactionNumber: string;
        balance: import("@prisma/client-runtime-utils").Decimal;
        isVoided: boolean;
        voidedBy: string | null;
        voidedAt: Date | null;
        voidReason: string | null;
    }>;
    listTransactions(customerId?: string, branchId?: string, type?: string, startDate?: string, endDate?: string, page?: string, limit?: string): Promise<{
        items: ({
            branch: {
                name: string;
            } | null;
            customer: {
                name: string;
                taxId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            description: string;
            createdBy: string;
            branchId: string | null;
            notes: string | null;
            customerId: string;
            dueDate: Date | null;
            amount: import("@prisma/client-runtime-utils").Decimal;
            type: import("@prisma/client").$Enums.CustomerTransactionType;
            referenceId: string | null;
            referenceType: string | null;
            transactionDate: Date;
            transactionNumber: string;
            balance: import("@prisma/client-runtime-utils").Decimal;
            isVoided: boolean;
            voidedBy: string | null;
            voidedAt: Date | null;
            voidReason: string | null;
        })[];
        total: number;
        page: number;
        limit: number;
        totalPages: number;
    }>;
    voidTransaction(id: string, dto: VoidTransactionDto): Promise<{
        success: boolean;
    }>;
    createArea(dto: CreateCustomerAreaDto): Promise<{
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        code: string;
        description: string | null;
        deletedAt: Date | null;
        isActive: boolean;
    }>;
    listAreas(): Promise<({
        _count: {
            salespeople: number;
        };
        subAreas: {
            id: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            code: string;
            description: string | null;
            deletedAt: Date | null;
            areaId: string;
            isActive: boolean;
        }[];
    } & {
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        code: string;
        description: string | null;
        deletedAt: Date | null;
        isActive: boolean;
    })[]>;
    updateArea(id: string, dto: UpdateCustomerAreaDto): Promise<{
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        code: string;
        description: string | null;
        deletedAt: Date | null;
        isActive: boolean;
    }>;
    deleteArea(id: string): Promise<{
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        code: string;
        description: string | null;
        deletedAt: Date | null;
        isActive: boolean;
    }>;
    createSubArea(dto: CreateCustomerSubAreaDto): Promise<{
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        code: string;
        description: string | null;
        deletedAt: Date | null;
        areaId: string;
        isActive: boolean;
    }>;
    listSubAreas(areaId?: string): Promise<({
        _count: {
            salespeople: number;
        };
        area: {
            id: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            code: string;
            description: string | null;
            deletedAt: Date | null;
            isActive: boolean;
        };
    } & {
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        code: string;
        description: string | null;
        deletedAt: Date | null;
        areaId: string;
        isActive: boolean;
    })[]>;
    updateSubArea(id: string, dto: UpdateCustomerSubAreaDto): Promise<{
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        code: string;
        description: string | null;
        deletedAt: Date | null;
        areaId: string;
        isActive: boolean;
    }>;
    deleteSubArea(id: string): Promise<{
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        code: string;
        description: string | null;
        deletedAt: Date | null;
        areaId: string;
        isActive: boolean;
    }>;
    createSalesperson(dto: CreateSalespersonDto): Promise<{
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        code: string;
        email: string | null;
        deletedAt: Date | null;
        phone: string | null;
        areaId: string | null;
        subAreaId: string | null;
        commissionRate: import("@prisma/client-runtime-utils").Decimal;
        isActive: boolean;
    }>;
    listSalespeople(areaId?: string, subAreaId?: string): Promise<({
        _count: {
            sales: number;
        };
        area: {
            id: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            code: string;
            description: string | null;
            deletedAt: Date | null;
            isActive: boolean;
        } | null;
        subArea: {
            id: string;
            name: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            code: string;
            description: string | null;
            deletedAt: Date | null;
            areaId: string;
            isActive: boolean;
        } | null;
    } & {
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        code: string;
        email: string | null;
        deletedAt: Date | null;
        phone: string | null;
        areaId: string | null;
        subAreaId: string | null;
        commissionRate: import("@prisma/client-runtime-utils").Decimal;
        isActive: boolean;
    })[]>;
    updateSalesperson(id: string, dto: UpdateSalespersonDto): Promise<{
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        code: string;
        email: string | null;
        deletedAt: Date | null;
        phone: string | null;
        areaId: string | null;
        subAreaId: string | null;
        commissionRate: import("@prisma/client-runtime-utils").Decimal;
        isActive: boolean;
    }>;
    deleteSalesperson(id: string): Promise<{
        id: string;
        name: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        code: string;
        email: string | null;
        deletedAt: Date | null;
        phone: string | null;
        areaId: string | null;
        subAreaId: string | null;
        commissionRate: import("@prisma/client-runtime-utils").Decimal;
        isActive: boolean;
    }>;
    getAgingReport(): Promise<{
        customerId: string;
        customerName: string;
        taxId: string | null;
        currentBalance: import("@prisma/client-runtime-utils").Decimal;
        creditLimit: import("@prisma/client-runtime-utils").Decimal;
        daysOverdue: number;
        overdueAmount: import("@prisma/client-runtime-utils").Decimal;
    }[]>;
}
