import { z } from 'zod';
export declare const createProductSchema: z.ZodObject<{
    description: z.ZodString;
    description_es: z.ZodOptional<z.ZodString>;
    description_en: z.ZodOptional<z.ZodString>;
    description_pt: z.ZodOptional<z.ZodString>;
    codigoArancelario: z.ZodString;
    paisOrigen: z.ZodString;
    price_a: z.ZodNumber;
    price_b: z.ZodNumber;
    price_c: z.ZodNumber;
    price_d: z.ZodNumber;
    price_e: z.ZodNumber;
    barcodes: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    categoryId: z.ZodOptional<z.ZodString>;
    brandId: z.ZodOptional<z.ZodString>;
    forceCreate: z.ZodOptional<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    description: string;
    codigoArancelario: string;
    paisOrigen: string;
    price_a: number;
    price_b: number;
    price_c: number;
    price_d: number;
    price_e: number;
    description_es?: string | undefined;
    description_en?: string | undefined;
    description_pt?: string | undefined;
    categoryId?: string | undefined;
    brandId?: string | undefined;
    barcodes?: string[] | undefined;
    forceCreate?: boolean | undefined;
}, {
    description: string;
    codigoArancelario: string;
    paisOrigen: string;
    price_a: number;
    price_b: number;
    price_c: number;
    price_d: number;
    price_e: number;
    description_es?: string | undefined;
    description_en?: string | undefined;
    description_pt?: string | undefined;
    categoryId?: string | undefined;
    brandId?: string | undefined;
    barcodes?: string[] | undefined;
    forceCreate?: boolean | undefined;
}>;
export type CreateProductDto = z.infer<typeof createProductSchema>;
