import { z } from 'zod';
export declare const updateProductSchema: z.ZodObject<{
    description: z.ZodOptional<z.ZodString>;
    description_es: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    description_en: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    description_pt: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    codigoArancelario: z.ZodOptional<z.ZodString>;
    paisOrigen: z.ZodOptional<z.ZodString>;
    price_a: z.ZodOptional<z.ZodNumber>;
    price_b: z.ZodOptional<z.ZodNumber>;
    price_c: z.ZodOptional<z.ZodNumber>;
    price_d: z.ZodOptional<z.ZodNumber>;
    price_e: z.ZodOptional<z.ZodNumber>;
    barcodes: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    categoryId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    brandId: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    forceCreate: z.ZodOptional<z.ZodOptional<z.ZodBoolean>>;
}, "strip", z.ZodTypeAny, {
    description?: string | undefined;
    description_es?: string | undefined;
    description_en?: string | undefined;
    description_pt?: string | undefined;
    codigoArancelario?: string | undefined;
    paisOrigen?: string | undefined;
    price_a?: number | undefined;
    price_b?: number | undefined;
    price_c?: number | undefined;
    price_d?: number | undefined;
    price_e?: number | undefined;
    categoryId?: string | undefined;
    brandId?: string | undefined;
    barcodes?: string[] | undefined;
    forceCreate?: boolean | undefined;
}, {
    description?: string | undefined;
    description_es?: string | undefined;
    description_en?: string | undefined;
    description_pt?: string | undefined;
    codigoArancelario?: string | undefined;
    paisOrigen?: string | undefined;
    price_a?: number | undefined;
    price_b?: number | undefined;
    price_c?: number | undefined;
    price_d?: number | undefined;
    price_e?: number | undefined;
    categoryId?: string | undefined;
    brandId?: string | undefined;
    barcodes?: string[] | undefined;
    forceCreate?: boolean | undefined;
}>;
export type UpdateProductDto = z.infer<typeof updateProductSchema>;
