export enum PermissionKey {
  // General
  MANAGE_TENANT = 'MANAGE_TENANT',
  MANAGE_USERS = 'MANAGE_USERS',

  // Products
  VIEW_COSTS = 'VIEW_COSTS',
  EDIT_PRODUCTS = 'EDIT_PRODUCTS',
  DELETE_PRODUCTS = 'DELETE_PRODUCTS',
  BULK_EDIT_PRICES = 'BULK_EDIT_PRICES',
  VIEW_PRICES = 'VIEW_PRICES',

  // Sales
  CREATE_SALE = 'CREATE_SALE',
  VIEW_SALES = 'VIEW_SALES',
  EDIT_SALES = 'EDIT_SALES',
  APPROVE_SALES = 'APPROVE_SALES',
  VOID_SALES = 'VOID_SALES',
  MANAGE_CLIENTS = 'MANAGE_CLIENTS',
  VIEW_CLIENTS = 'VIEW_CLIENTS',
  APPROVE_CREDIT = 'APPROVE_CREDIT',

  // Inventory
  VIEW_INVENTORY = 'VIEW_INVENTORY',
  ADJUST_INVENTORY = 'ADJUST_INVENTORY',
  VIEW_BRANCHES = 'VIEW_BRANCHES',
  MANAGE_BRANCHES = 'MANAGE_BRANCHES',

  // Traffic
  MANAGE_TRAFFIC = 'MANAGE_TRAFFIC',
  VIEW_TRAFFIC = 'VIEW_TRAFFIC',

  // POS
  MANAGE_POS = 'MANAGE_POS',
  MANAGE_CASH_REGISTERS = 'MANAGE_CASH_REGISTERS',
}
