import { PrismaService } from '../prisma/prisma.service';
import { CreateShipmentDto } from './dto/create-shipment.dto';
import { ShipmentQueryDto } from './dto/shipment-query.dto';
import { UpdateTrafficDocsDto } from './dto/update-shipment.dto';
import { Prisma } from '@prisma/client';
import { NotificationsService } from '../notifications/notifications.service';
export declare class TrafficService {
    private readonly prisma;
    private readonly notificationsService;
    private readonly logger;
    constructor(prisma: PrismaService, notificationsService: NotificationsService);
    create(createDto: CreateShipmentDto, tenantId: string, userId: string): Promise<{
        items: {
            id: string;
            tenantId: string;
            weight: Prisma.Decimal | null;
            volume: Prisma.Decimal | null;
            productId: string;
            quantity: Prisma.Decimal;
            tariffCode: string | null;
            saleItemId: string;
            shipmentId: string;
        }[];
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        createdBy: string;
        shipmentNumber: string;
        dispatchDate: Date | null;
        destination: string | null;
        vesselName: string | null;
        voyageNumber: string | null;
        portOfLoading: string | null;
        portOfDischarge: string | null;
        etd: Date | null;
        eta: Date | null;
        actualArrival: Date | null;
        containerNumber: string | null;
        sealNumber: string | null;
        containerType: string | null;
        containerSize: string | null;
        dmcNumber: string | null;
        blNumber: string | null;
        bookingNumber: string | null;
        freeSaleCert: string | null;
        carrierName: string | null;
        driverName: string | null;
        plateNumber: string | null;
    }>;
    findAll(query: ShipmentQueryDto, tenantId: string): Promise<{
        items: ({
            _count: {
                items: number;
            };
        } & {
            id: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            createdBy: string;
            shipmentNumber: string;
            dispatchDate: Date | null;
            destination: string | null;
            vesselName: string | null;
            voyageNumber: string | null;
            portOfLoading: string | null;
            portOfDischarge: string | null;
            etd: Date | null;
            eta: Date | null;
            actualArrival: Date | null;
            containerNumber: string | null;
            sealNumber: string | null;
            containerType: string | null;
            containerSize: string | null;
            dmcNumber: string | null;
            blNumber: string | null;
            bookingNumber: string | null;
            freeSaleCert: string | null;
            carrierName: string | null;
            driverName: string | null;
            plateNumber: string | null;
        })[];
        meta: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    }>;
    getStats(tenantId: string): Promise<{
        DRAFT: number;
        PACKED: number;
        DISPATCHED: number;
        IN_TRANSIT: number;
        ARRIVED: number;
        DELIVERED: number;
        TOTAL: number;
    }>;
    findOne(id: string, tenantId: string): Promise<{
        [x: string]: ({
            id: string;
            tenantId: string;
            weight: Prisma.Decimal | null;
            volume: Prisma.Decimal | null;
            productId: string;
            quantity: Prisma.Decimal;
            tariffCode: string | null;
            saleItemId: string;
            shipmentId: string;
        } | {
            id: string;
            tenantId: string;
            weight: Prisma.Decimal | null;
            volume: Prisma.Decimal | null;
            productId: string;
            quantity: Prisma.Decimal;
            tariffCode: string | null;
            saleItemId: string;
            shipmentId: string;
        })[] | ({
            id: string;
            status: string;
            createdAt: Date;
            tenantId: string;
            description: string | null;
            createdBy: string;
            shipmentId: string;
            location: string | null;
            eventDate: Date;
        } | {
            id: string;
            status: string;
            createdAt: Date;
            tenantId: string;
            description: string | null;
            createdBy: string;
            shipmentId: string;
            location: string | null;
            eventDate: Date;
        })[] | {
            id: string;
            tenantId: string;
            weight: Prisma.Decimal | null;
            volume: Prisma.Decimal | null;
            productId: string;
            quantity: Prisma.Decimal;
            tariffCode: string | null;
            saleItemId: string;
            shipmentId: string;
        }[] | {
            id: string;
            status: string;
            createdAt: Date;
            tenantId: string;
            description: string | null;
            createdBy: string;
            shipmentId: string;
            location: string | null;
            eventDate: Date;
        }[];
        [x: number]: never;
        [x: symbol]: never;
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        createdBy: string;
        shipmentNumber: string;
        dispatchDate: Date | null;
        destination: string | null;
        vesselName: string | null;
        voyageNumber: string | null;
        portOfLoading: string | null;
        portOfDischarge: string | null;
        etd: Date | null;
        eta: Date | null;
        actualArrival: Date | null;
        containerNumber: string | null;
        sealNumber: string | null;
        containerType: string | null;
        containerSize: string | null;
        dmcNumber: string | null;
        blNumber: string | null;
        bookingNumber: string | null;
        freeSaleCert: string | null;
        carrierName: string | null;
        driverName: string | null;
        plateNumber: string | null;
    }>;
    updateDocs(id: string, updateDto: UpdateTrafficDocsDto, tenantId: string, userId: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        createdBy: string;
        shipmentNumber: string;
        dispatchDate: Date | null;
        destination: string | null;
        vesselName: string | null;
        voyageNumber: string | null;
        portOfLoading: string | null;
        portOfDischarge: string | null;
        etd: Date | null;
        eta: Date | null;
        actualArrival: Date | null;
        containerNumber: string | null;
        sealNumber: string | null;
        containerType: string | null;
        containerSize: string | null;
        dmcNumber: string | null;
        blNumber: string | null;
        bookingNumber: string | null;
        freeSaleCert: string | null;
        carrierName: string | null;
        driverName: string | null;
        plateNumber: string | null;
    }>;
    addEvent(shipmentId: string, dto: any, tenantId: string, userId: string): Promise<any>;
    updateStatus(id: string, status: string, tenantId: string, userId: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        createdBy: string;
        shipmentNumber: string;
        dispatchDate: Date | null;
        destination: string | null;
        vesselName: string | null;
        voyageNumber: string | null;
        portOfLoading: string | null;
        portOfDischarge: string | null;
        etd: Date | null;
        eta: Date | null;
        actualArrival: Date | null;
        containerNumber: string | null;
        sealNumber: string | null;
        containerType: string | null;
        containerSize: string | null;
        dmcNumber: string | null;
        blNumber: string | null;
        bookingNumber: string | null;
        freeSaleCert: string | null;
        carrierName: string | null;
        driverName: string | null;
        plateNumber: string | null;
    }>;
    getPackingList(id: string, tenantId: string): Promise<{
        shipmentNumber: any;
        destination: any;
        carrier: any;
        booking: any;
        container: any;
        seal: any;
        groupedItems: Record<string, any[]>;
        totalItems: any;
        generatedAt: Date;
    }>;
    dispatch(id: string, tenantId: string, userId: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        createdBy: string;
        shipmentNumber: string;
        dispatchDate: Date | null;
        destination: string | null;
        vesselName: string | null;
        voyageNumber: string | null;
        portOfLoading: string | null;
        portOfDischarge: string | null;
        etd: Date | null;
        eta: Date | null;
        actualArrival: Date | null;
        containerNumber: string | null;
        sealNumber: string | null;
        containerType: string | null;
        containerSize: string | null;
        dmcNumber: string | null;
        blNumber: string | null;
        bookingNumber: string | null;
        freeSaleCert: string | null;
        carrierName: string | null;
        driverName: string | null;
        plateNumber: string | null;
    }>;
    generateDmcPdf(id: string, tenantId: string): Promise<Buffer>;
    generateBlPdf(id: string, tenantId: string): Promise<Buffer>;
    generateFreeSalePdf(id: string, tenantId: string): Promise<Buffer>;
}
