import type { Response } from 'express';
import { TrafficService } from './traffic.service';
import type { CreateShipmentDto } from './dto/create-shipment.dto';
import type { ShipmentQueryDto } from './dto/shipment-query.dto';
import type { UpdateTrafficDocsDto } from './dto/update-shipment.dto';
export declare class TrafficController {
    private readonly trafficService;
    constructor(trafficService: TrafficService);
    private getContext;
    create(createDto: CreateShipmentDto): Promise<{
        items: {
            id: string;
            tenantId: string;
            weight: import("@prisma/client-runtime-utils").Decimal | null;
            volume: import("@prisma/client-runtime-utils").Decimal | null;
            productId: string;
            quantity: import("@prisma/client-runtime-utils").Decimal;
            tariffCode: string | null;
            saleItemId: string;
            shipmentId: string;
        }[];
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        createdBy: string;
        shipmentNumber: string;
        dispatchDate: Date | null;
        destination: string | null;
        vesselName: string | null;
        voyageNumber: string | null;
        portOfLoading: string | null;
        portOfDischarge: string | null;
        etd: Date | null;
        eta: Date | null;
        actualArrival: Date | null;
        containerNumber: string | null;
        sealNumber: string | null;
        containerType: string | null;
        containerSize: string | null;
        dmcNumber: string | null;
        blNumber: string | null;
        bookingNumber: string | null;
        freeSaleCert: string | null;
        carrierName: string | null;
        driverName: string | null;
        plateNumber: string | null;
    }>;
    findAll(query: ShipmentQueryDto): Promise<{
        items: ({
            _count: {
                items: number;
            };
        } & {
            id: string;
            status: string;
            createdAt: Date;
            updatedAt: Date;
            tenantId: string;
            createdBy: string;
            shipmentNumber: string;
            dispatchDate: Date | null;
            destination: string | null;
            vesselName: string | null;
            voyageNumber: string | null;
            portOfLoading: string | null;
            portOfDischarge: string | null;
            etd: Date | null;
            eta: Date | null;
            actualArrival: Date | null;
            containerNumber: string | null;
            sealNumber: string | null;
            containerType: string | null;
            containerSize: string | null;
            dmcNumber: string | null;
            blNumber: string | null;
            bookingNumber: string | null;
            freeSaleCert: string | null;
            carrierName: string | null;
            driverName: string | null;
            plateNumber: string | null;
        })[];
        meta: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    }>;
    getStats(): Promise<{
        DRAFT: number;
        PACKED: number;
        DISPATCHED: number;
        IN_TRANSIT: number;
        ARRIVED: number;
        DELIVERED: number;
        TOTAL: number;
    }>;
    findOne(id: string): Promise<{
        [x: string]: ({
            id: string;
            tenantId: string;
            weight: import("@prisma/client-runtime-utils").Decimal | null;
            volume: import("@prisma/client-runtime-utils").Decimal | null;
            productId: string;
            quantity: import("@prisma/client-runtime-utils").Decimal;
            tariffCode: string | null;
            saleItemId: string;
            shipmentId: string;
        } | {
            id: string;
            tenantId: string;
            weight: import("@prisma/client-runtime-utils").Decimal | null;
            volume: import("@prisma/client-runtime-utils").Decimal | null;
            productId: string;
            quantity: import("@prisma/client-runtime-utils").Decimal;
            tariffCode: string | null;
            saleItemId: string;
            shipmentId: string;
        })[] | ({
            id: string;
            status: string;
            createdAt: Date;
            tenantId: string;
            description: string | null;
            createdBy: string;
            shipmentId: string;
            location: string | null;
            eventDate: Date;
        } | {
            id: string;
            status: string;
            createdAt: Date;
            tenantId: string;
            description: string | null;
            createdBy: string;
            shipmentId: string;
            location: string | null;
            eventDate: Date;
        })[] | {
            id: string;
            tenantId: string;
            weight: import("@prisma/client-runtime-utils").Decimal | null;
            volume: import("@prisma/client-runtime-utils").Decimal | null;
            productId: string;
            quantity: import("@prisma/client-runtime-utils").Decimal;
            tariffCode: string | null;
            saleItemId: string;
            shipmentId: string;
        }[] | {
            id: string;
            status: string;
            createdAt: Date;
            tenantId: string;
            description: string | null;
            createdBy: string;
            shipmentId: string;
            location: string | null;
            eventDate: Date;
        }[];
        [x: number]: never;
        [x: symbol]: never;
    } & {
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        createdBy: string;
        shipmentNumber: string;
        dispatchDate: Date | null;
        destination: string | null;
        vesselName: string | null;
        voyageNumber: string | null;
        portOfLoading: string | null;
        portOfDischarge: string | null;
        etd: Date | null;
        eta: Date | null;
        actualArrival: Date | null;
        containerNumber: string | null;
        sealNumber: string | null;
        containerType: string | null;
        containerSize: string | null;
        dmcNumber: string | null;
        blNumber: string | null;
        bookingNumber: string | null;
        freeSaleCert: string | null;
        carrierName: string | null;
        driverName: string | null;
        plateNumber: string | null;
    }>;
    updateDocs(id: string, updateDto: UpdateTrafficDocsDto): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        createdBy: string;
        shipmentNumber: string;
        dispatchDate: Date | null;
        destination: string | null;
        vesselName: string | null;
        voyageNumber: string | null;
        portOfLoading: string | null;
        portOfDischarge: string | null;
        etd: Date | null;
        eta: Date | null;
        actualArrival: Date | null;
        containerNumber: string | null;
        sealNumber: string | null;
        containerType: string | null;
        containerSize: string | null;
        dmcNumber: string | null;
        blNumber: string | null;
        bookingNumber: string | null;
        freeSaleCert: string | null;
        carrierName: string | null;
        driverName: string | null;
        plateNumber: string | null;
    }>;
    dispatch(id: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        createdBy: string;
        shipmentNumber: string;
        dispatchDate: Date | null;
        destination: string | null;
        vesselName: string | null;
        voyageNumber: string | null;
        portOfLoading: string | null;
        portOfDischarge: string | null;
        etd: Date | null;
        eta: Date | null;
        actualArrival: Date | null;
        containerNumber: string | null;
        sealNumber: string | null;
        containerType: string | null;
        containerSize: string | null;
        dmcNumber: string | null;
        blNumber: string | null;
        bookingNumber: string | null;
        freeSaleCert: string | null;
        carrierName: string | null;
        driverName: string | null;
        plateNumber: string | null;
    }>;
    updateStatus(id: string, status: string): Promise<{
        id: string;
        status: string;
        createdAt: Date;
        updatedAt: Date;
        tenantId: string;
        createdBy: string;
        shipmentNumber: string;
        dispatchDate: Date | null;
        destination: string | null;
        vesselName: string | null;
        voyageNumber: string | null;
        portOfLoading: string | null;
        portOfDischarge: string | null;
        etd: Date | null;
        eta: Date | null;
        actualArrival: Date | null;
        containerNumber: string | null;
        sealNumber: string | null;
        containerType: string | null;
        containerSize: string | null;
        dmcNumber: string | null;
        blNumber: string | null;
        bookingNumber: string | null;
        freeSaleCert: string | null;
        carrierName: string | null;
        driverName: string | null;
        plateNumber: string | null;
    }>;
    addEvent(id: string, dto: any): Promise<any>;
    getPackingList(id: string): Promise<{
        shipmentNumber: any;
        destination: any;
        carrier: any;
        booking: any;
        container: any;
        seal: any;
        groupedItems: Record<string, any[]>;
        totalItems: any;
        generatedAt: Date;
    }>;
    getDmcPdf(id: string, res: Response): Promise<void>;
    getBlPdf(id: string, res: Response): Promise<void>;
    getFreeSalePdf(id: string, res: Response): Promise<void>;
}
