"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PermissionKey = void 0;
var PermissionKey;
(function (PermissionKey) {
    PermissionKey["MANAGE_TENANT"] = "MANAGE_TENANT";
    PermissionKey["MANAGE_USERS"] = "MANAGE_USERS";
    PermissionKey["VIEW_COSTS"] = "VIEW_COSTS";
    PermissionKey["EDIT_PRODUCTS"] = "EDIT_PRODUCTS";
    PermissionKey["DELETE_PRODUCTS"] = "DELETE_PRODUCTS";
    PermissionKey["BULK_EDIT_PRICES"] = "BULK_EDIT_PRICES";
    PermissionKey["VIEW_PRICES"] = "VIEW_PRICES";
    PermissionKey["CREATE_SALE"] = "CREATE_SALE";
    PermissionKey["VIEW_SALES"] = "VIEW_SALES";
    PermissionKey["EDIT_SALES"] = "EDIT_SALES";
    PermissionKey["APPROVE_SALES"] = "APPROVE_SALES";
    PermissionKey["VOID_SALES"] = "VOID_SALES";
    PermissionKey["MANAGE_CLIENTS"] = "MANAGE_CLIENTS";
    PermissionKey["VIEW_CLIENTS"] = "VIEW_CLIENTS";
    PermissionKey["APPROVE_CREDIT"] = "APPROVE_CREDIT";
    PermissionKey["VIEW_INVENTORY"] = "VIEW_INVENTORY";
    PermissionKey["ADJUST_INVENTORY"] = "ADJUST_INVENTORY";
    PermissionKey["VIEW_BRANCHES"] = "VIEW_BRANCHES";
    PermissionKey["MANAGE_BRANCHES"] = "MANAGE_BRANCHES";
    PermissionKey["MANAGE_TRAFFIC"] = "MANAGE_TRAFFIC";
    PermissionKey["VIEW_TRAFFIC"] = "VIEW_TRAFFIC";
    PermissionKey["MANAGE_POS"] = "MANAGE_POS";
    PermissionKey["MANAGE_CASH_REGISTERS"] = "MANAGE_CASH_REGISTERS";
})(PermissionKey || (exports.PermissionKey = PermissionKey = {}));
//# sourceMappingURL=permission-key.enum.js.map